apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - image: spring-k8s/kafka-consumer:snapshot
        name: kafka-consumer
        resources: {}
status: {}
