apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres-db
  name: postgres-db-service
spec:
  type: NodePort
  ports:
    - port: 5432
      name: kafka-port
      protocol: TCP
  selector:
    app: postgres-db
    id: "0"
