apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  strategy: { }
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - image: spring-k8s/kafka-producer:snapshot
          name: kafka-producer
          resources: { }
